import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Aladdin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid grid-cols-12 w-screen h-screen">
        <Sidebar></Sidebar>
        {children}
      </body>
    </html>
  );
}
